### ISSUE TITLE
phpMyAdmin 5.0.4

### ISSUE THREAD

**Issue by petecassetta** [iusrepo/phpMyAdmin50#1]
This is supposed to be the last release of the 5.0 branch (moving to 5.1 after this). Would request that it be packaged for Red Hat/CentOS 7, as it fixes several bugs and 5.0.2 users are getting a nag screen about the availability of 5.0.4.

https://www.phpmyadmin.net/news/2020/10/15/phpmyadmin-497-and-504-are-released/

I'm happy to test the packages once available in testing of course.

**Comment by petecassetta** [comment]
This was requested a few months ago. Hopefully it would be easy to build the new package as it's just a minor bug fix release. But some of the bugs are pretty significant and are bothering our customers. We've been telling them to wait for the packaged 5.0.4. Any chance this can be done soon? As noted before, I'm happy to test.

**Comment by carlwgeorge** [comment]
I just updated the package and published it to the testing repo.  If you try it out and confirm it works as expected, I'll promote it to the main repo early.

**Comment by petecassetta** [comment]
I tested for awhile, and everything looks correct. The package installs and works as expected. I think it's safe to promote to the main repo when you have time. Thanks so much!

**Comment by carlwgeorge** [comment]
Thanks for testing.  I've promoted phpMyAdmin50-5.0.4-1.el7.ius to the main repo.
