### ISSUE TITLE
Package conflicts with PHP 7.4 installed

### ISSUE THREAD

**Issue by avodlan** [iusrepo/phpMyAdmin50#2]
Installing phpMyAdmin50 with PHP 7.4 from iUS repository throws dependency error.

```
Resolving Dependencies
--> Running transaction check
---> Package phpMyAdmin50.noarch 0:5.0.4-1.el7.ius will be installed
--> Processing Dependency: php-zip for package: phpMyAdmin50-5.0.4-1.el7.ius.noarch
--> Running transaction check
---> Package php73-common.x86_64 0:7.3.27-1.el7.ius will be installed
--> Processing Conflict: php74-common-7.4.15-1.el7.ius.x86_64 conflicts php-common < 7.4.15-1.el7.ius
--> Processing Conflict: php74-common-7.4.15-1.el7.ius.x86_64 conflicts php73-common
--> Finished Dependency Resolution
Error: php74-common conflicts with php73-common-7.3.27-1.el7.ius.x86_64
```

If you install it with `rpm --nodeps` it will work.

**Comment by carlwgeorge** [comment]
Multiple IUS packages can satisfy the php-zip requirement.  Yum gets confused and tries to pick packages from different PHP stacks.  Use dnf or explicitly install the PHP you want to use.  This is described in the [FAQs](https://ius.io/faq#why-does-yum-fail-with-conflict-errors-when-installing-a-non-ius-package), albeit from the perspective of non-IUS packages.  If you'd like to add another FAQ item describing this specifically, please [send a pull request](https://github.com/iusrepo/iusrepo.github.io).
